In [10]:
! python -m pip install nashpy

    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/c3/_jn4lv5d6q3bvt7s8607jvmm0000gn/T/pip-install-70npcsa8/nashpy_15120d126c3f428e98290a9fa59fac09/setup.py'"'"'; __file__='"'"'/private/var/folders/c3/_jn4lv5d6q3bvt7s8607jvmm0000gn/T/pip-install-70npcsa8/nashpy_15120d126c3f428e98290a9fa59fac09/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/c3/_jn4lv5d6q3bvt7s8607jvmm0000gn/T/pip-pip-egg-info-0blg5ld6
         cwd: /private/var/folders/c3/_jn4lv5d6q3bvt7s8607jvmm0000gn/T/pip-install-70npcsa8/nashpy_15120d126c3f428e98290a9fa59fac09/
    Complete output (5 lines):
    Traceback (most recent call last):


In [15]:
import numpy as np
import nashpy as nash

In [16]:
A = np.array([[2,0],[4,2]]) # A is the row player
B = np.array([[4,2],[2,0]]) # B is the column player
game1 = nash.Game(A,B)
game1

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]

In [17]:
# Find the Nash Equilibrium with Support Enumeration
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

(array([0., 1.]), array([1., 0.]))
